# Generated by Django 4.0.1 on 2022-01-27 06:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('mob', models.CharField(max_length=14, primary_key=True, serialize=False)),
                ('eid', models.CharField(max_length=15, unique=True)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('logtime', models.DateField(primary_key=True, serialize=False)),
                ('mask', models.BooleanField()),
                ('temp', models.DecimalField(decimal_places=3, max_digits=5)),
                ('access', models.BooleanField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='facedectapi.user')),
            ],
        ),
    ]
