# Generated by Django 4.0.1 on 2022-02-01 05:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('facedectapi', '0003_alter_log_logtime'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='logtime',
            field=models.DateTimeField(primary_key=True, serialize=False),
        ),
    ]
